curl -X GET "http://localhost:8080/buerger" -v -H "accept:application/json"
curl -X GET "http://localhost:8080/gewerbliche_anbieter" -v -H "accept:application/json"
curl -X GET "http://localhost:8080/wohnorte" -v -H "accept:application/json"
curl -X GET "http://localhost:8080/spezialisierungen" -v -H "accept:application/json"
curl -X GET "http://localhost:8080/events" -v -H "accept:application/json"
curl -X GET "http://localhost:8080/gruppen" -v -H "accept:application/json"
curl -X GET "http://localhost:8080/anzeigen" -v -H "accept:application/json"
curl -X GET "http://localhost:8080/anzeigen/nachrichten" -v -H "accept:application/json"
curl -X GET "http://localhost:8080/events/bewertungen" -v -H "accept:application/json"
curl -X POST "http://localhost:8080/buerger" -v -H "accept:application/json" -H "Content-Type: multipart/form-data" -F "email=aaa@aaa.aa" -F "passwort=AA999" -F "vorname=Max" -F "nachname=Mustermann" -F "wohnortid=1" -F "berufbezeichnung=streamer"
curl -X POST "http://localhost:8080/gewerbliche_anbieter" -v -H "accept:application/json" -H "Content-Type: multipart/form-data" -F "gruendungsjahr=2020" -F "email=ggg@gg.gg" -F "passwort=AA999" -F "vorname=Maxim" -F "nachname=Mustermann" -F "wohnortid=2" -F "berufbezeichnung=streamer"
curl -X POST "http://localhost:8080/wohnorte" -v -H "accept:application/json" -H "Content-Type: multipart/form-data" -F "strasse=neustrasse" -F "hausnummer=11A" -F "plz=12345" -F "stadt=Duesseldorf"
curl -X POST "http://localhost:8080/spezialisierungen" -v -H "accept:application/json" -H "Content-Type: multipart/form-data" -F "bezeichnung=EEEE"
curl -X POST "http://localhost:8080/events" -u "timmy@baby12.de:T89IO" -v -H "accept:application/json" -H "Content-Type: multipart/form-data" -F "titel=Drum shop" -F "beschreibung=A new drum world for everyone" -F "startdatum=2024-05-06" -F "wohnortid=3"
curl -X POST "http://localhost:8080/gruppen" -u "timmy@baby12.de:T89IO" -v -H "accept:application/json" -H "Content-Type: multipart/form-data" -F "bezeichnung=HHU" -F "sprache=english" -F "ist_privat=false"
curl -X POST "http://localhost:8080/anzeigen" -u "timmy@baby12.de:T89IO" -v -H "accept:application/json" -H "Content-Type: multipart/form-data" -F "titel=tables for free" -F "beschreibung=available tables for free"
curl -X DELETE "http://localhost:8080/anzeigen/3" -u "babyy@example.com:B00A00" -v -H "accept:application/json" -H "Content-Type: multipart/form-data" -F "anzeigeid=3"
curl -X POST "http://localhost:8080/anzeigen/2/nachrichten" -u "babyy@example.com:B00A00" -v -H "accept:application/json" -H "Content-Type: multipart/form-data" -F "text=Pls check your ib"
curl -X DELETE "http://localhost:8080/anzeigen/2/nachrichten/2" -u "aaa999@dhl.de:AA999" -v -H "accept:application/json" -H "Content-Type: multipart/form-data" -F "anzeigeid=2" -F "nachrichtid=2"
curl -X POST "http://localhost:8080/events/2/bewertungen" -u "aaa999@dhl.de:AA999" -v -H "accept:application/json" -H "Content-Type: multipart/form-data" -F "eventid=2" -F "punktzahl=5"
curl -X PATCH "http://localhost:8080/anzeigen/1" -u "timmy@baby12.de:T89IO" -v -H "accept:application/json" -H "Content-Type: multipart/form-data" -F "titel=BMW for sale"